In [3]:
# pip install numpy
import numpy as np



In [8]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
np.zeros([5, 7, 8,]) #numpy trabaja con arreglos multidimesionales

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [15]:
np.zeros((5,7,8,)) # funciona tanto con listas o tuplas

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [16]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np.arange(4, 20) # intervalos [4,20[ intervalo abierto

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
np.arange(-8) #

array([], dtype=int32)

In [25]:
np.arange(-8, 1) # del -8 al 0

array([-8, -7, -6, -5, -4, -3, -2, -1,  0])

In [26]:
np.arange(0, 20, 2) # el tercer parametro es el salto en cada numero

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.arange(0, 20, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

In [32]:
np.arange(-12, 1, 0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5])

In [35]:
arreglo_pares = np.arange(0,20,2)
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimesiones = np.zeros((2, 3, 4))
print(arreglo_tres_dimesiones.shape)

10
10
(2, 3, 4)


In [40]:
arreglo_pares.reshape(5, 2) # cambiar las dimesiones, es el minimo comum multiplo

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [39]:
arreglo_pares.reshape(2, 5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [46]:
arreglo_ejemplo = np.arange(24)
arreglo_ejemplo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
arreglo_ejemplo.reshape(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
arreglo_ejemplo.reshape(6,4).reshape(3,8) # OJOOOOOOOOOOOO



array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
arreglo_ejemplo.reshape(4,6)

In [ ]:
arreglo_ejemplo.reshape(12,2)

In [ ]:
arreglo_ejemplo.reshape(2,12)

In [ ]:
arreglo_ejemplo.reshape(3,8)

In [49]:
arreglo_ejemplo.reshape(8,3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [50]:
arreglo_ejemplo.reshape(3,4,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [51]:
arreglo_ejemplo.reshape(2,4,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [52]:
arreglo_ejemplo.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [53]:
arreglo_ejemplo.reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [54]:
arreglo_ejemplo.reshape(2,2,2,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [ ]:
arreglo_ejemplo.reshape(3,2,2,2)

In [55]:
arreglo_ejemplo.reshape(2,3,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [59]:
arreglo_ejemplo.reshape(2,2,3,2)

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [61]:
a = np.array([10,10,10]) # arreglo
b = np.array([5,5,5]) 

In [62]:
#suma
a + b

array([15, 15, 15])

In [63]:
# resta
a - b

array([5, 5, 5])

In [65]:
# multiplicacion
a * b

array([50, 50, 50])

In [66]:
# division
a / b

array([2., 2., 2.])

In [67]:
# modulo
a % b

array([0, 0, 0], dtype=int32)

In [94]:
arreglo_uno = np.arange(-2,100,0.6)
arreglo_dos = np.arange(0,102,0.6)
arreglo_dos.size

170

In [82]:
arreglo_uno+ arreglo_dos

array([ -4. ,  -2.8,  -1.6,  -0.4,   0.8,   2. ,   3.2,   4.4,   5.6,
         6.8,   8. ,   9.2,  10.4,  11.6,  12.8,  14. ,  15.2,  16.4,
        17.6,  18.8,  20. ,  21.2,  22.4,  23.6,  24.8,  26. ,  27.2,
        28.4,  29.6,  30.8,  32. ,  33.2,  34.4,  35.6,  36.8,  38. ,
        39.2,  40.4,  41.6,  42.8,  44. ,  45.2,  46.4,  47.6,  48.8,
        50. ,  51.2,  52.4,  53.6,  54.8,  56. ,  57.2,  58.4,  59.6,
        60.8,  62. ,  63.2,  64.4,  65.6,  66.8,  68. ,  69.2,  70.4,
        71.6,  72.8,  74. ,  75.2,  76.4,  77.6,  78.8,  80. ,  81.2,
        82.4,  83.6,  84.8,  86. ,  87.2,  88.4,  89.6,  90.8,  92. ,
        93.2,  94.4,  95.6,  96.8,  98. ,  99.2, 100.4, 101.6, 102.8,
       104. , 105.2, 106.4, 107.6, 108.8, 110. , 111.2, 112.4, 113.6,
       114.8, 116. , 117.2, 118.4, 119.6, 120.8, 122. , 123.2, 124.4,
       125.6, 126.8, 128. , 129.2, 130.4, 131.6, 132.8, 134. , 135.2,
       136.4, 137.6, 138.8, 140. , 141.2, 142.4, 143.6, 144.8, 146. ,
       147.2, 148.4,

In [87]:
arreglo_uno.reshape(17,2,5)


array([[[-2. , -1.4, -0.8, -0.2,  0.4,  1. ,  1.6,  2.2,  2.8,  3.4,
          4. ,  4.6,  5.2,  5.8,  6.4,  7. ,  7.6],
        [ 8.2,  8.8,  9.4, 10. , 10.6, 11.2, 11.8, 12.4, 13. , 13.6,
         14.2, 14.8, 15.4, 16. , 16.6, 17.2, 17.8],
        [18.4, 19. , 19.6, 20.2, 20.8, 21.4, 22. , 22.6, 23.2, 23.8,
         24.4, 25. , 25.6, 26.2, 26.8, 27.4, 28. ],
        [28.6, 29.2, 29.8, 30.4, 31. , 31.6, 32.2, 32.8, 33.4, 34. ,
         34.6, 35.2, 35.8, 36.4, 37. , 37.6, 38.2],
        [38.8, 39.4, 40. , 40.6, 41.2, 41.8, 42.4, 43. , 43.6, 44.2,
         44.8, 45.4, 46. , 46.6, 47.2, 47.8, 48.4]],

       [[49. , 49.6, 50.2, 50.8, 51.4, 52. , 52.6, 53.2, 53.8, 54.4,
         55. , 55.6, 56.2, 56.8, 57.4, 58. , 58.6],
        [59.2, 59.8, 60.4, 61. , 61.6, 62.2, 62.8, 63.4, 64. , 64.6,
         65.2, 65.8, 66.4, 67. , 67.6, 68.2, 68.8],
        [69.4, 70. , 70.6, 71.2, 71.8, 72.4, 73. , 73.6, 74.2, 74.8,
         75.4, 76. , 76.6, 77.2, 77.8, 78.4, 79. ],
        [79.6, 80.2, 80.8, 81.

In [88]:
arreglo_dos.reshape(2,5,17) # suma de matrices de 3 dimensiones


array([[[-2. , -1.4, -0.8, -0.2,  0.4,  1. ,  1.6,  2.2,  2.8,  3.4,
          4. ,  4.6,  5.2,  5.8,  6.4,  7. ,  7.6],
        [ 8.2,  8.8,  9.4, 10. , 10.6, 11.2, 11.8, 12.4, 13. , 13.6,
         14.2, 14.8, 15.4, 16. , 16.6, 17.2, 17.8],
        [18.4, 19. , 19.6, 20.2, 20.8, 21.4, 22. , 22.6, 23.2, 23.8,
         24.4, 25. , 25.6, 26.2, 26.8, 27.4, 28. ],
        [28.6, 29.2, 29.8, 30.4, 31. , 31.6, 32.2, 32.8, 33.4, 34. ,
         34.6, 35.2, 35.8, 36.4, 37. , 37.6, 38.2],
        [38.8, 39.4, 40. , 40.6, 41.2, 41.8, 42.4, 43. , 43.6, 44.2,
         44.8, 45.4, 46. , 46.6, 47.2, 47.8, 48.4]],

       [[49. , 49.6, 50.2, 50.8, 51.4, 52. , 52.6, 53.2, 53.8, 54.4,
         55. , 55.6, 56.2, 56.8, 57.4, 58. , 58.6],
        [59.2, 59.8, 60.4, 61. , 61.6, 62.2, 62.8, 63.4, 64. , 64.6,
         65.2, 65.8, 66.4, 67. , 67.6, 68.2, 68.8],
        [69.4, 70. , 70.6, 71.2, 71.8, 72.4, 73. , 73.6, 74.2, 74.8,
         75.4, 76. , 76.6, 77.2, 77.8, 78.4, 79. ],
        [79.6, 80.2, 80.8, 81.

In [95]:
arreglo_dos.reshape(2,5,17) + arreglo_uno.reshape(2,5,17)

array([[[ -2. ,  -0.8,   0.4,   1.6,   2.8,   4. ,   5.2,   6.4,   7.6,
           8.8,  10. ,  11.2,  12.4,  13.6,  14.8,  16. ,  17.2],
        [ 18.4,  19.6,  20.8,  22. ,  23.2,  24.4,  25.6,  26.8,  28. ,
          29.2,  30.4,  31.6,  32.8,  34. ,  35.2,  36.4,  37.6],
        [ 38.8,  40. ,  41.2,  42.4,  43.6,  44.8,  46. ,  47.2,  48.4,
          49.6,  50.8,  52. ,  53.2,  54.4,  55.6,  56.8,  58. ],
        [ 59.2,  60.4,  61.6,  62.8,  64. ,  65.2,  66.4,  67.6,  68.8,
          70. ,  71.2,  72.4,  73.6,  74.8,  76. ,  77.2,  78.4],
        [ 79.6,  80.8,  82. ,  83.2,  84.4,  85.6,  86.8,  88. ,  89.2,
          90.4,  91.6,  92.8,  94. ,  95.2,  96.4,  97.6,  98.8]],

       [[100. , 101.2, 102.4, 103.6, 104.8, 106. , 107.2, 108.4, 109.6,
         110.8, 112. , 113.2, 114.4, 115.6, 116.8, 118. , 119.2],
        [120.4, 121.6, 122.8, 124. , 125.2, 126.4, 127.6, 128.8, 130. ,
         131.2, 132.4, 133.6, 134.8, 136. , 137.2, 138.4, 139.6],
        [140.8, 142. , 143.2, 14

In [100]:
# multiplicacion escalares
print(a *10)
print(a - 7)
print(a + 2)
print(a / 2)
# print(a = 2) # no vale
print (a % 3)


[100 100 100]
[3 3 3]
[12 12 12]
[5. 5. 5.]
[1 1 1]


In [182]:
# elegir numeros mayores a ...
arreglo_muestra = np.arange(20).reshape(5,2,2) # Arreglo de 3 dimensiones

arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [103]:
resp = arreglo_muestra >6 # comparacion con cada uno de ellos
resp2 = arreglo_muestra <14

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [104]:
arreglo_muestra[resp] # si envio un arreglo de verdaderos y false el devolveera los valores true....valores mayores a 5 O_O

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [180]:
arreglo_muestra[resp*resp2]



array([ 3,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [186]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [185]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [187]:
A.dot(B) # producto punto

array([[ 6,  7],
       [26, 31]])

In [188]:
np.dot(A,B) # producto punto

array([[ 6,  7],
       [26, 31]])

In [189]:
B.dot(A) # recordar que el orden si importa en operaciones ocn matrices

array([[10, 19],
       [14, 27]])

In [190]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [191]:
arreglo_doce.sum() # suma del arreglo del 0 al 11

66

In [193]:
arreglo_doce.min() # menor numero

0

In [194]:
arreglo_doce.max() # mayor nuemro

11

In [201]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [204]:
arreglo_doce.reshape(3,2,2).sum(axis =0)

array([[12, 15],
       [18, 21]])

In [203]:
arreglo_doce.reshape(3,2,2).sum(axis =1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [205]:
arreglo_doce.reshape(3,2,2).sum(axis =2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

In [213]:
np.arange(24).reshape(3,2,2,2).sum(axis =3)

array([[[ 1,  5],
        [ 9, 13]],

       [[17, 21],
        [25, 29]],

       [[33, 37],
        [41, 45]]])