In [1]:
import numpy as np


In [2]:
arreglo_0_a_90_grados = np.array([0,30,45,60,90]) #utilizar listas siempre
arreglo_0_a_90_grados

array([ 0, 30, 45, 60, 90])

In [3]:
radianes = arreglo_0_a_90_grados*np.pi / 180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [4]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
np.sin(arreglo_0_a_90_grados) # no hay chance

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [6]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [7]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [41]:
arreglo_random = np.random.randint( # ingresar el parametro de numeros que se quiere -1
    11 # enteros + hasta
) # [0,11[
arreglo_random

10

In [43]:
arreglo_random = np.random.randint(
    -1, # enteros +hasta
    2 #enteros + hasta
)
arreglo_random # [-1,2[

-1

In [51]:
arreglo_random = np.random.randint(
    0, # minimo
    11,# maximo
    3 #numero de randomicos
)
arreglo_random


array([4, 6, 1])

In [52]:
arreglo_random.mean() # media

3.6666666666666665

In [53]:
np.median(arreglo_random) # mediana

4.0

In [54]:
np.std(arreglo_random) # promedio

2.0548046676563256

In [55]:
np.var(arreglo_random) # varianza


4.222222222222222

In [56]:
np.mean(arreglo_random) # es lo mismo de arreglo_random.mean pero mejor asi

3.6666666666666665