In [75]:
import numpy as np
import pandas as pd


In [4]:
np.zeros((10,), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
vector = np.zeros(10)
vector[5]=1
vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [14]:
vector_50 = np.arange(50)
vector_50

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
vector_50[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [20]:
matriz = np.arange(9)
matriz.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
arreglo = [1,2,0,0,4,0]
bindices_zero = (arreglo == 0)
indices_zero = numpy.arange(len(arreglo))[bindices_zero]

    

NameError: name 'numpy' is not defined

In [ ]:
# 6

In [51]:
# 7
matriz_id = np.identity(3)
matriz_id




array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
# 8
arreglo_random = np.random.randint(
    0, # minimo
    11,# maximo
    27 #numero de randomicos
)
#arreglo_random.size
matriz_rand = arreglo_random.reshape(3,3,3)
matriz_rand

array([[[ 8,  1,  3],
        [ 5,  3,  5],
        [ 4, 10,  7]],

       [[ 5,  4, 10],
        [ 6,  0,  5],
        [10,  4,  6]],

       [[ 4,  6,  8],
        [ 9,  8,  0],
        [ 9,  4,  5]]])

In [74]:
# 9
matriz = np.arange(100)
matriz_10_10 = matriz.reshape(10,10)
print(np.max(matriz_10_10))
print(np.min(matriz_10_10))


99
0


In [80]:
# 10
from scipy import ndimage
from scipy import misc

imagen = misc.face()
imagen

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

In [83]:
# 11
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

serie_a = pd.Series(mylist)
serie_b = pd.Series(myarr)
serie_c = pd.Series(mydict)
print(serie_a)
print(serie_b)
print(serie_c)





0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [90]:
# 12
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice
df1 = pd.DataFrame(ser)
df1



0
a   0
b   1
c   2
e   3
d   4
f   5
g   6
h   7
i   8
j   9
k  10
l  11
m  12
n  13
o  14
p  15
q  16
r  17
s  18
t  19
u  20
v  21
w  22
x  23
y  24
z  25

In [98]:
# 13
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
pd.concat([ser1, ser2], axis=1)



0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [102]:
# 14
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])






In [103]:
# 22
path='BostonHousing.csv'
columnas = ['crim','zn','indus','chas','nox']
df2 = pd.read_csv( 
        path,
        nrows = 10,
        usecols = columnas)
df2

crim    zn  indus  chas    nox
0  0.00632  18.0   2.31     0  0.538
1  0.02731   0.0   7.07     0  0.469
2  0.02729   0.0   7.07     0  0.469
3  0.03237   0.0   2.18     0  0.458
4  0.06905   0.0   2.18     0  0.458
5  0.02985   0.0   2.18     0  0.458
6  0.08829  12.5   7.87     0  0.524
7  0.14455  12.5   7.87     0  0.524
8  0.21124  12.5   7.87     0  0.524
9  0.17004  12.5   7.87     0  0.524

0